-- Espelho verbatim da migração aplicada 20260730154052 (motor3_tabelas_restantes) — reconstruído de supabase_migrations em 2026-08-07 (higiene, varredura noturna)
create schema if not exists motor3;
create table if not exists motor3.t_fatores_tdc (row_id bigint generated always as identity primary key, "id" text, "categoria" text, "fator" text, "valor" text, "lado" text, "dispositivo" text, "fonte_tabela_csv" text, "chunk_id" text, "eval_id" text, "verificado" text);
alter table motor3.t_fatores_tdc enable row level security;
create policy sel_t_fatores_tdc on motor3.t_fatores_tdc for select to authenticated using (true);
create table if not exists motor3.t_fi_incentivo_doacao (row_id bigint generated always as identity primary key, "finalidade" text, "fi" numeric, "inciso" text, "condicao" text);
alter table motor3.t_fi_incentivo_doacao enable row level security;
create policy sel_t_fi_incentivo_doacao on motor3.t_fi_incentivo_doacao for select to authenticated using (true);
create table if not exists motor3.t_fi_zepec_area_lpuos (row_id bigint generated always as identity primary key, "faixa_area_lote_m2" text, "fi" numeric, "inciso" text);
alter table motor3.t_fi_zepec_area_lpuos enable row level security;
create policy sel_t_fi_zepec_area_lpuos on motor3.t_fi_zepec_area_lpuos for select to authenticated using (true);
create table if not exists motor3.t_ipca_numero_indice_ibge (row_id bigint generated always as identity primary key, "mes" text, "numero_indice" numeric);
alter table motor3.t_ipca_numero_indice_ibge enable row level security;
create policy sel_t_ipca_numero_indice_ibge on motor3.t_ipca_numero_indice_ibge for select to authenticated using (true);
create table if not exists motor3.t_iptu_fator_obsolescencia (row_id bigint generated always as identity primary key, "idade" numeric, "fator_tipo12_ab" numeric, "fator_demais" numeric, "dispositivo" text, "lei" text);
alter table motor3.t_iptu_fator_obsolescencia enable row level security;
create policy sel_t_iptu_fator_obsolescencia on motor3.t_iptu_fator_obsolescencia for select to authenticated using (true);
create table if not exists motor3.t_iptu_fatores_terreno (row_id bigint generated always as identity primary key, "fator" text, "condicao" text, "valor" numeric, "dispositivo" text, "lei" text);
alter table motor3.t_iptu_fatores_terreno enable row level security;
create policy sel_t_iptu_fatores_terreno on motor3.t_iptu_fatores_terreno for select to authenticated using (true);
create table if not exists motor3.t_iptu_valor_construcao_m2 (row_id bigint generated always as identity primary key, "tipo" numeric, "padrao" text, "subdivisao_1a_brl" numeric, "subdivisao_2a_brl" numeric, "alem_2a_brl" numeric, "dispositivo" text, "lei" text);
alter table motor3.t_iptu_valor_construcao_m2 enable row level security;
create policy sel_t_iptu_valor_construcao_m2 on motor3.t_iptu_valor_construcao_m2 for select to authenticated using (true);
create table if not exists motor3.t_limiar_parque_art127 (row_id bigint generated always as identity primary key, "ano_ref" numeric, "limiar_rs_m2" numeric, "fonte" text, "dispositivo" text);
alter table motor3.t_limiar_parque_art127 enable row level security;
create policy sel_t_limiar_parque_art127 on motor3.t_limiar_parque_art127 for select to authenticated using (true);
create table if not exists motor3.t_q14_reajuste_anual (row_id bigint generated always as identity primary key, "ano_ref" numeric, "percentual" numeric, "fator_anual" numeric, "fator_acumulado" numeric, "decreto" text, "vigencia_inicio" date, "dispositivo" text);
alter table motor3.t_q14_reajuste_anual enable row level security;
create policy sel_t_q14_reajuste_anual on motor3.t_q14_reajuste_anual for select to authenticated using (true);
create table if not exists motor3.t_q14_valor_terreno (row_id bigint generated always as identity primary key, "setor" numeric, "quadra" numeric, "sql" numeric, "codlog" numeric, "valor_m2_brl" text);
alter table motor3.t_q14_valor_terreno enable row level security;
create policy sel_t_q14_valor_terreno on motor3.t_q14_valor_terreno for select to authenticated using (true);
create table if not exists motor3.t_quadro2a_ca_macroarea (row_id bigint generated always as identity primary key, "macrozona" text, "macroarea" text, "ca_minimo" text, "ca_basico" text, "ca_maximo" text, "gabarito_altura_m" text, "num_max_pavimentos" text, "nota" text);
alter table motor3.t_quadro2a_ca_macroarea enable row level security;
create policy sel_t_quadro2a_ca_macroarea on motor3.t_quadro2a_ca_macroarea for select to authenticated using (true);
create table if not exists motor3.t_quadro3_ca_por_zona (row_id bigint generated always as identity primary key, "zona" text, "ca_min" text, "ca_basico" text, "ca_max" text, "ca_max_nota" text);
alter table motor3.t_quadro3_ca_por_zona enable row level security;
create policy sel_t_quadro3_ca_por_zona on motor3.t_quadro3_ca_por_zona for select to authenticated using (true);
create table if not exists motor3.t_quadro5_fator_social_fs (row_id bigint generated always as identity primary key, "categoria_uso" text, "fs" text);
alter table motor3.t_quadro5_fator_social_fs enable row level security;
create policy sel_t_quadro5_fator_social_fs on motor3.t_quadro5_fator_social_fs for select to authenticated using (true);
create table if not exists motor3.t_quadro6_fator_planejamento_fp (row_id bigint generated always as identity primary key, "macrozona" text, "macroarea" text, "subarea" text, "fp_r" numeric, "fp_nr" numeric);
alter table motor3.t_quadro6_fator_planejamento_fp enable row level security;
create policy sel_t_quadro6_fator_planejamento_fp on motor3.t_quadro6_fator_planejamento_fp for select to authenticated using (true);
create table if not exists motor3.t_quadro7_parques (row_id bigint generated always as identity primary key, "codigo" text, "situacao" text, "categoria" text, "proposto" text, "revisar" text, "local_bruto" text, "endereco_bruto" text);
alter table motor3.t_quadro7_parques enable row level security;
create policy sel_t_quadro7_parques on motor3.t_quadro7_parques for select to authenticated using (true);
